# Generated by Django 4.2.4 on 2023-08-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0002_product_created_on_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_on',
            field=models.TimeField(auto_now=True),
        ),
    ]
