# Generated by Django 4.2.4 on 2023-08-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0004_alter_product_created_on_alter_product_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_on',
            field=models.TimeField(auto_created=True),
        ),
    ]
